language: node_js
node_js: "6.5"
services:
- mongodb
- redis-server
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
    - mongodb-3.2-precise
    - ubuntu-toolchain-r-test
    packages:
    - mongodb-org-server
    - g++-4.8
